### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign n3wscott shashwathi tanzeeb
/cc n3wscott shashwathi tanzeeb

### CODE REVIEW

**Comment by shashwathi** [comment]
@mattmoor : This PR deletes the ingress label. I think we want keep these changes.

**Comment by n3wscott** [comment]
> @mattmoor : This PR deletes the ingress label. I think we want keep these changes.

you will have to fix this upstream. These are all vendor changes.

**Comment by andrew-su** [comment]
https://github.com/knative/net-contour/pull/126 should re-add the labels to the generated configs when running `update-deps.sh`

**Pull request merged**
