### PR TITLE
[release-0.13] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign n3wscott shashwathi tanzeeb
/cc n3wscott shashwathi tanzeeb

### CODE REVIEW

**Comment by mattmoor** [comment]
This is because we didn't freeze Serving to `release-0.13`.  @n3wscott think tomles can do that for us this time around?

**Comment by n3wscott** [comment]
Yes

**Comment by mattmoor** [comment]
😍

**Pull request closed without merging**
