### PR TITLE
Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign shashwathi tanzeeb
/cc shashwathi tanzeeb

### CODE REVIEW

**Comment by mattmoor** [comment]
@shashwathi this is real, these functions moved to pkg's kmeta package.  Up for a PR?

**Comment by shashwathi** [comment]
Yeah I will do that 👍

**Comment by shashwathi** [comment]
My bad I saw the build fail and I assumed it was scripts :-/

**Comment by mattmoor** [comment]
No worries, it is more often than it should be. :(

**Pull request closed without merging**
